printer/urls.py
from django.urls import path
from .views import index

app_name = 'printer'

urlpatterns = [
  path('', index, name='index')
]

sabeb/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('printer.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

printer/models.py
from django.db import models

# Create your models here.

printer/forms.py
from django import forms
import subprocess

COLOR = [
    ('RGB', 'Color'),
    ('Gray', 'Grayscale'),
]
SIZE = [
    ('A4', 'A4'),
    ('Letter', 'Letter'),
]
QUALITY = [
    ('Draft', 'Draft'),
    ('Normal', 'Normal'),
    ('High', 'High'),
]


class UploadFileForm(forms.Form):
    file = forms.FileField(label='')
    file.widget.attrs['class'] = 'form-control form-control-lg shadow mb-3'
    color = forms.CharField(label='Color Mode: ',
                            widget=forms.Select(choices=COLOR))
    printQuality = forms.CharField(
        label='Print Quality: ', widget=forms.Select(choices=QUALITY))
    pageSize = forms.CharField(
        label='Page size: ', widget=forms.Select(choices=SIZE))

printer/views.py
from django.shortcuts import render
from .forms import UploadFileForm
from django.core.files.storage import FileSystemStorage
from django.conf import settings
import subprocess


def index(request):
    printer = subprocess.check_output(['lpstat', '-p']).decode().split()[1]
    options = subprocess.check_output(
        ['lpoptions', '-l']).decode().split()
    print(options)
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            color_mode = request.POST.get('color', 'RGB')
            print_quality = request.POST['printQuality']
            page_size = request.POST['pageSize']
            print(color_mode, print_quality, page_size)
            call_bash(request.FILES['file'], printer, color_mode, print_quality, page_size)
    else:
        form = UploadFileForm()
    return render(request, 'index.html', {'form': form, 'printer': printer})


def call_bash(file, print, color_mode, print_quality, page_size):
    fs = FileSystemStorage()
    filename = fs.save(file.name, file)
    abs_path = settings.MEDIA_ROOT + "/" + filename
    color = "ColorModel=" + color_mode
    quality = "Print=" + print_quality
    size = "PageSize=" + page_size
    subprocess.Popen(['lp', '-d', print, '-o', color, '-o', quality, '-o', size, abs_path])
    return

printer/templates/index.html
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
  <title>Printer Sabeb</title>
</head>

<body>
  <div class="container">
    <div class="position-absolute top-50 start-50 translate-middle">
      <h1 class="text-center">Printer Sabeb</h1>
      <h4 class="text-center">Printer : {{printer}}</h4>

      <form action="{% url 'printer:index' %}" method="POST" class="mt-4" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.file }}
        Color Mode: {{ form.color }}
        Print Quality: {{ form.printQuality }}
        Page Size: {{ form.pageSize }}
        <div class="d-grid gap-2 col-6 mx-auto mt-4">
          <button type="submit" class="btn-lg btn-primary">Print</button>
        </div>
      </form>

    </div>
  </div>


  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
    crossorigin="anonymous"></script>
</body>

</html>